default_experiment: java

reporting:
    rebenchdb:
        # this url needs to point to the API endpoint
        db_url: https://rebench.dev/rebenchdb
        repo_url: https://gitlab.com/smarr/benchmarking-demo
        record_all: true # make sure everything is recorded
        project_name: BenchmarkingDemo

.awfy_benchmarks: &BENCHMARKS
  # - DeltaBlue:  {extra_args: 12000}
  # - Richards:   {extra_args: 100}
  # - Json:       {extra_args: 100}
  # - CD:         {extra_args: 250}
  # - Havlak:     {extra_args: 1500}
  # - Bounce:     {extra_args: 1500}
  # - List:       {extra_args: 1500}
  # - Mandelbrot: {extra_args: 500}
  # - NBody:      {extra_args: 250000}
  # - Permute:    {extra_args: 1000}
  - Queens:     {extra_args: 1000}
  - Sieve:      {extra_args: 3000}
  - Storage:    {extra_args: 600}
  - Towers:     {extra_args: 600}

benchmark_suites:
  awfy-java:
    gauge_adapter: RebenchLog
    command: " -cp awfy/benchmarks/Java/benchmarks.jar Harness %(benchmark)s %(iterations)s "
    iterations: 100
    benchmarks: *BENCHMARKS
    min_iteration_time: 1
    env:
      JAVA_HOME: ~/.asdf/installs/java/temurin-22.0.2+9
      PATH: ~/.asdf/installs/java/temurin-22.0.2+9/bin:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    build:
      - cd awfy/benchmarks/Java && ant clean && ant jar

# StepE2: Add Executor for Java
executors:
  java:
    executable: java

# StepE2: Add Experiment for Day-to-Day Benchmarking
experiments:
  java:
    suites: [awfy-java]
    executions: [java]

  # StepP5: add experimental settings for paper-quality results
